apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fanout-ingress
  namespace: hello-world-preprod
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /aaa/
        pathType: Prefix
        backend:
          service:
            name: frontend1-service
            port:
              number: 80
      - path: /bbb/
        pathType: Prefix
        backend:
          service:
            name: frontend2-service
            port:
              number: 80
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: backend-api-service1
            port:
              number: 3000