apiVersion: v1
kind: Service
metadata:
  name: frontend-service2
  namespace: hello-world-preprod
  labels:
    environment: preprod
spec:
  selector:
    app: frontend2
    environment: preprod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
