# .github/workflows/deploy.yml
#
name: Deploy Hello World to EKS

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/hello-world:latest .
        docker push ghcr.io/${{ github.repository }}/hello-world:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name education-eks-VxAaQBxE --region eu-west-1

    - name: Delete configMap
      run: |
        kubectl delete configmap ingress-config -n hello-world-preprod

    - name: Create configMap
      run: |
        kubectl create configmap ingress-config --from-file=config.json -n hello-world-preprod

    - name: Create Deployment1
      run: | 
         kubectl apply -f k8s/frontend-deployment1.yaml -n hello-world-preprod

    - name: Create Deployment2
      run: | 
         kubectl apply -f k8s/frontend-deployment2.yaml -n hello-world-preprod

    - name: Rollout Deployment1
      run: | 
         kubectl rollout restart deployment deployfrontend1 --namespace=hello-world-preprod

    - name: Rollout Deployment2
      run: | 
          kubectl rollout restart deployment deployfrontend2 --namespace=hello-world-preprod

  #  - name: Delete service frontend1-service
  #    run: |
  #      kubectl delete service/frontend1-service -n hello-world-preprod

    - name: Deploy SERVICE frontend1-service to EKS
      run: |
        kubectl apply -f k8s/frontend1-service.yaml -n hello-world-preprod

  #  - name: Delete service frontend2-service
  #    run: |
  #      kubectl delete service/frontend2-service -n hello-world-preprod

    - name: Deploy SERVICE frontend2-service to EKS
      run: |
        kubectl apply -f k8s/frontend2-service.yaml -n hello-world-preprod

    - name: Deploy Ingress
      run: |
        kubectl apply -f k8s/fanout-ingress.yaml -n hello-world-preprod


